#' Ghoshdastidar hypothesis testing for large random graphs.
#'
#' Given two lists of graphs generated by the inhomogeneous random graph model,
#' \code{ghoshdastidar} tests if they were generated by the same parameters.
#'
#' @param Graphs1 a list of undirected Graphs.
#' If each graph has the  attribute \code{eigenvalues} containing its
#' eigenvalues , such values will be used to
#' compute their spectral density.
#'
#' @param Graphs2 a list of undirected Graphs.
#' If each graph has the  attribute \code{eigenvalues} containing its
#' eigenvalues , such values will be used to
#' compute their spectral density.
#'
#' @param maxBoot integer indicating the number of bootstrap resamples (default
#' is \code{300}).
#'
#' @param alpha the significance level for the test (default is \code{0.05}).
#'
#' @param two.sample logical. If TRUE the sets contain only one graph each. If
#' FALSE the sets contain more than one graph each (default is \code{FALSE}).
#'
#' @param printResult logical indicating if the test must print the result
#' (default is \code{FALSE}).
#'
#'
#' @return A list with class "htest" containing the following components:
#' \itemize{
#' \item{\code{statistic:}}{ the T-value of the test.}
#' \item{\code{p.value:}}{ the p-value of the test (only returned when the parameter
#' 'two.sample' is \code{FALSE}).}
#' \item{\code{method:}}{ a string indicating the used method.}
#' \item{\code{data.name:}}{ a string with the data's name(s).}
#' }
#'
#' @references
#' Ghoshdastidar, Debarghya, et al. "Two-sample tests for large random graphs
#' using network statistics". arXiv preprint arXiv:1705.06168 (2017).
#'
#' Ghoshdastidar, Debarghya, et al. "Two-sample hypothesis testing for
#' inhomogeneous random graphs". arXiv preprint, arXiv:1707.00833 (2017).
#'
#' @examples
#' \donttest{
#' set.seed(1)
#'
#' ## test for sets with only one graph each under H0
#' Graphs1 <- Graphs2 <- list()
#' Graphs1[[1]] <- igraph::erdos.renyi.game(300, 0.6)
#' Graphs2[[1]] <- igraph::erdos.renyi.game(300, 0.6)
#' D <- graph.ghoshdastidar.test(Graphs1, Graphs2, two.sample= TRUE, printResult = TRUE)
#'
#' ## test for sets with only one graph each under H1
#' Graphs1 <- Graphs2 <- list()
#' Graphs1[[1]] <- igraph::erdos.renyi.game(300, 0.6)
#' Graphs2[[1]] <- igraph::erdos.renyi.game(300, 0.7)
#' D <- graph.ghoshdastidar.test(Graphs1, Graphs2, two.sample= TRUE, printResult = TRUE)
#' }
#'
#' @export
graph.ghoshdastidar.test <- function(Graphs1, Graphs2, maxBoot = 300, alpha = 0.05, two.sample = FALSE, printResult = FALSE)
{

  if(!valid.input(Graphs1) || !valid.input(Graphs2)) stop("The inputs should be a list of igraph objects!")

  data.name <- paste(deparse(substitute(Graphs1)),"and",deparse(substitute(Graphs2)))

  Graphs1 <- graphList.to.adjList(Graphs1)
  Graphs2 <- graphList.to.adjList(Graphs2)

  D <- ghosh.test(Graphs1, Graphs2)
  ###
  statistic <- D
  names(statistic) <- "T"
  method <- "Ghoshdastidar hypothesis testing for large random graphs"

  if(!two.sample){
    test_distribution <- ghosh.sampling.distribution(Graphs1,Graphs2,maxBoot)
    p_val <- mean(test_distribution >= D)
    rval <- list(statistic=statistic, p.value=p_val, method=method, data.name=data.name)
  }
  else{
    rval <- list(statistic=statistic, method=method, data.name=data.name)
  }
  class(rval) <- "htest"
  return(rval)
}

# Auxiliary for Ghoshdastidar method. Ghoshdastidar test itself according to article.
ghosh.test <- function(x, y){
  m <- min(length(x),length(y))

  x <- lapply(x, function(s){
    s2 <- s
    s2[lower.tri(s2)]<-0
    eval.parent(substitute(s<-s2))
  })

  y <- lapply(y, function(s){
    s2 <- s
    s2[lower.tri(s2)]<-0
    eval.parent(substitute(s<-s2))
  })

  n <- dim(x[[1]])[1]
  Sm1 <- matrix(0,1,m)
  Sp1 <- matrix(0,1,m)
  Sm2 <- matrix(0,1,m)
  Sp2 <- matrix(0,1,m)

  for(i in 1:m){
    Sm1[i] <- sum(x[[i]]*(x[[i]]%*%x[[i]]))/(6*choose(n,3))
    Sp1[i] <- Sm1[i]*log(n)/choose(n,3)

    Sm2[i] <- sum(y[[i]]*(y[[i]]%*%y[[i]]))/(6*choose(n,3))
    Sp2[i] <- Sm2[i]*log(n)/choose(n,3)
  }

  num <- abs(sum(Sm1-Sm2));
  den <- 2*(sqrt(sum(Sp1))+sqrt(sum(Sp2)))

  if(den == 0) den <- 1
  stat <- abs(num/den)
  return(stat)
}


## Auxiliary for Ghoshdastidar method. Boostrap for the test.
ghosh.sampling.distribution <- function(x, y, maxPer = 300)
{
  m1 <- length(x)
  m2 <- length(y)
  test_distribution = c()
  for (i_per in 1:maxPer){
    xe <- sample(append(x,y), m1, replace = TRUE)
    ye <- sample(append(x,y), m2, replace = TRUE)
    test_distribution[i_per] <- ghosh.test(xe, ye)
  }
  return(sort(test_distribution))
}
